__author__ = 'gkour'


class ConfigPhysics:
    SPACE_SIZE = 20
    NUM_FATHERS = 50
    ETERNITY = 100000
    SLIPPERY_SPACE = False
    FOOD_CREATURE_RATIO = 0.5
    INITIAL_FOOD_AMOUNT = NUM_FATHERS * 10
    SOUND_LASTING_TIME = 2


class ConfigBiology:
    BASE_LIFE_EXPECTANCY = 0
    DNA_SIZE = 6
    MOVE_ENERGY = 0.5
    FIGHT_ENERGY = MOVE_ENERGY * 5
    INITIAL_ENERGY = 50
    MATE_ENERGY = MOVE_ENERGY * 10
    MATURITY_AGE = 12  # int(BASE_LIFE_EXPECTANCY / 5)
    BASE_LEARN_FREQ = 5
    BASE_VISION_RANGE = 2
    MEAL_SIZE = 6
    WORK_ENERGY = 3
    BASE_MEMORY_SIZE = 30
    VOCALIZE_ENERGY = 1
    EVOLUTION_MUTATION_STD = 0.5


class ConfigBrain:
    BASE_REWARD_DISCOUNT = 0.99
    BASE_LEARNING_RATE = 5e-4
    BASE_BRAIN_STRUCTURE_PARAM = 10
    BASE_EPSILON = 0.1
